using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace NdJson.SourceGeneration
{
    internal sealed partial class Emitter
    {
        private const string Ndj = "global::NdJson.";
        private const string Support = "global::NdJson.Serialization.NdjsonGeneratedSupport.";

        private readonly Compilation _compilation;
        private readonly KnownSymbols _known;
        private readonly Dictionary<INamedTypeSymbol, string> _converterNames;
        private readonly Dictionary<INamedTypeSymbol, string> _enumHelpers = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);
        private readonly List<INamedTypeSymbol> _enumOrder = new List<INamedTypeSymbol>();

        internal Emitter(Compilation compilation, KnownSymbols known, Dictionary<INamedTypeSymbol, string> converterNames)
        {
            _compilation = compilation;
            _known = known;
            _converterNames = converterNames;
        }

        internal string EmitConverter(TypeModel model)
        {
            StringBuilder sb = new StringBuilder(8192);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();

            string indent = string.Empty;
            if (model.ConverterNamespace.Length > 0)
            {
                sb.Append("namespace ").AppendLine(model.ConverterNamespace);
                sb.AppendLine("{");
                indent = "    ";
            }

            if (model.IsPolymorphic)
            {
                EmitPolymorphicConverter(sb, indent, model);

                bool selfDerived = model.Derived.Any(d => SymbolEqualityComparer.Default.Equals(d.Type, model.Symbol));
                if (selfDerived && !model.Symbol.IsAbstract && model.Symbol.TypeKind != TypeKind.Interface)
                {
                    EmitObjectConverter(sb, indent, model, model.ConverterName + "Members");
                }
            }
            else
            {
                EmitObjectConverter(sb, indent, model, model.ConverterName);
            }

            if (model.ConverterNamespace.Length > 0)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private void EmitObjectConverter(StringBuilder sb, string indent, TypeModel model, string className)
        {
            string type = model.TypeName;
            List<string> staticFields = new List<string>();
            StringBuilder body = new StringBuilder(4096);
            int temp = 0;

            for (int i = 0; i < model.Members.Count; i++)
            {
                MemberModel member = model.Members[i];
                staticFields.Add("private static readonly byte[] __n" + i + " = " + Support + "EncodeName(" + Literal(member.JsonName) + ");");
                staticFields.Add("private static readonly byte[] __k" + i + " = " + Support + "EncodeUtf8(" + Literal(member.JsonName) + ");");

                if (member.ExplicitConverter != null)
                {
                    member.ConverterFieldIndex = i;
                    staticFields.Add("private static readonly " + Display.FullName(member.ExplicitConverter) + " __c" + i + " = new " + Display.FullName(member.ExplicitConverter) + "();");
                }
            }

            body.Append(indent).AppendLine("    public override void Write(ref " + Ndj + "JsonWriter writer, in " + type + " value, " + Ndj + "NdjsonOptions options)");
            body.Append(indent).AppendLine("    {");
            if (!model.IsValueType)
            {
                body.Append(indent).AppendLine("        if (value == null)");
                body.Append(indent).AppendLine("        {");
                body.Append(indent).AppendLine("            writer.WriteNull();");
                body.Append(indent).AppendLine("            return;");
                body.Append(indent).AppendLine("        }");
                body.AppendLine();
            }

            body.Append(indent).AppendLine("        writer.WriteStartObject();");
            body.Append(indent).AppendLine("        WriteMembers(ref writer, in value, options);");
            body.Append(indent).AppendLine("        writer.WriteEndObject();");
            body.Append(indent).AppendLine("    }");
            body.AppendLine();

            body.Append(indent).AppendLine("    public void WriteMembers(ref " + Ndj + "JsonWriter writer, in " + type + " value, " + Ndj + "NdjsonOptions options)");
            body.Append(indent).AppendLine("    {");
            EmitWriteMembersBody(body, indent + "        ", model, ref temp);
            body.Append(indent).AppendLine("    }");
            body.AppendLine();

            body.Append(indent).AppendLine("    void global::NdJson.Serialization.INdjsonObjectConverter.WriteMembers(ref " + Ndj + "JsonWriter writer, object value, " + Ndj + "NdjsonOptions options)");
            body.Append(indent).AppendLine("    {");
            body.Append(indent).AppendLine("        " + type + " __typed = (" + type + ")value;");
            body.Append(indent).AppendLine("        WriteMembers(ref writer, in __typed, options);");
            body.Append(indent).AppendLine("    }");
            body.AppendLine();

            body.Append(indent).AppendLine("    public override " + type + " Read(ref " + Ndj + "JsonReader reader, " + Ndj + "NdjsonOptions options)");
            body.Append(indent).AppendLine("    {");
            EmitReadBody(body, indent + "        ", model, ref temp);
            body.Append(indent).AppendLine("    }");

            sb.Append(indent).AppendLine(model.Accessibility + " sealed class " + className + " : global::NdJson.Serialization.NdjsonConverter<" + type + ">, global::NdJson.Serialization.INdjsonObjectConverter");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    public static readonly " + className + " Instance = new " + className + "();");
            sb.AppendLine();
            foreach (string field in staticFields)
            {
                sb.Append(indent).Append("    ").AppendLine(field);
            }

            sb.AppendLine();
            sb.Append(body);
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private void EmitWriteMembersBody(StringBuilder sb, string indent, TypeModel model, ref int temp)
        {
            for (int i = 0; i < model.Members.Count; i++)
            {
                MemberModel member = model.Members[i];
                if (!member.CanRead)
                {
                    continue;
                }

                string access = "value." + member.MemberName;
                bool guarded = false;

                if (member.Ignore == IgnoreCondition.WhenWritingNull && CanBeNull(member.Type))
                {
                    sb.Append(indent).AppendLine("if (" + access + " != null)");
                    sb.Append(indent).AppendLine("{");
                    guarded = true;
                }
                else if (member.Ignore == IgnoreCondition.WhenWritingDefault)
                {
                    sb.Append(indent).AppendLine("if (" + NotDefaultExpression(member.Type, access) + ")");
                    sb.Append(indent).AppendLine("{");
                    guarded = true;
                }

                string guardIndent = guarded ? indent + "    " : indent;
                sb.Append(guardIndent).AppendLine("writer.WritePropertyName(__n" + i + ");");
                EmitWriteValue(sb, guardIndent, member.Type, access, member, ref temp);

                if (guarded)
                {
                    sb.Append(indent).AppendLine("}");
                }

                sb.AppendLine();
            }

            if (model.ExtensionData != null)
            {
                string extra = "value." + model.ExtensionData.MemberName;
                int id = temp++;
                sb.Append(indent).AppendLine("var __x" + id + " = " + extra + ";");
                sb.Append(indent).AppendLine("if (__x" + id + " != null)");
                sb.Append(indent).AppendLine("{");
                sb.Append(indent).AppendLine("    foreach (var __e" + id + " in __x" + id + ")");
                sb.Append(indent).AppendLine("    {");
                sb.Append(indent).AppendLine("        writer.WritePropertyName(__e" + id + ".Key);");
                EmitWriteValue(sb, indent + "        ", model.ExtensionValueType, "__e" + id + ".Value", null, ref temp);
                sb.Append(indent).AppendLine("    }");
                sb.Append(indent).AppendLine("}");
            }
        }

        private void EmitReadBody(StringBuilder sb, string indent, TypeModel model, ref int temp)
        {
            string type = model.TypeName;
            string defaultResult = model.IsValueType ? "default(" + type + ")" : "null";

            sb.Append(indent).AppendLine("if (!reader.BeginObject())");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    return " + defaultResult + ";");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();

            bool useLocals = model.UseObjectInitializer;
            List<MemberModel> writable = new List<MemberModel>();

            foreach (MemberModel member in model.Members)
            {
                if (member.CanWrite || member.ConstructorParameterIndex >= 0 || member.IsInitOnly)
                {
                    writable.Add(member);
                }
            }

            bool needsSeen = model.Members.Any(m => m.IsRequired) || useLocals;

            if (useLocals)
            {
                for (int i = 0; i < model.Members.Count; i++)
                {
                    MemberModel member = model.Members[i];
                    if (!writable.Contains(member))
                    {
                        continue;
                    }

                    sb.Append(indent).AppendLine(Display.FullName(member.Type) + " __v" + i + " = default(" + Display.FullName(member.Type) + ");");
                    sb.Append(indent).AppendLine("bool __s" + i + " = false;");
                }
            }
            else
            {
                sb.Append(indent).AppendLine(type + " __result = new " + type + "();");
                for (int i = 0; i < model.Members.Count; i++)
                {
                    if (model.Members[i].IsRequired)
                    {
                        sb.Append(indent).AppendLine("bool __s" + i + " = false;");
                    }
                }
            }

            if (model.ExtensionData != null)
            {
                sb.Append(indent).AppendLine(Display.FullName(model.ExtensionData.Type) + " __extra = " + (useLocals ? "default(" + Display.FullName(model.ExtensionData.Type) + ")" : "__result." + model.ExtensionData.MemberName) + ";");
            }

            sb.AppendLine();
            sb.Append(indent).AppendLine("while (reader.ReadNextProperty())");
            sb.Append(indent).AppendLine("{");

            string loop = indent + "    ";
            sb.Append(loop).AppendLine("global::System.ReadOnlySpan<byte> __name = reader.PropertyNameSpan;");
            sb.Append(loop).AppendLine("switch (__name.Length)");
            sb.Append(loop).AppendLine("{");

            IEnumerable<IGrouping<int, MemberModel>> byLength = model.Members
                .Where(m => writable.Contains(m))
                .GroupBy(m => Utf8Length(m.JsonName));

            foreach (IGrouping<int, MemberModel> group in byLength)
            {
                sb.Append(loop).AppendLine("    case " + group.Key + ":");
                foreach (MemberModel member in group)
                {
                    int index = model.Members.IndexOf(member);
                    sb.Append(loop).AppendLine("        if (" + Support + "NameEquals(__name, __k" + index + "))");
                    sb.Append(loop).AppendLine("        {");
                    sb.Append(loop).AppendLine("            reader.Advance();");
                    string target = useLocals ? "__v" + index : "__result." + member.MemberName;
                    EmitReadInto(sb, loop + "            ", member.Type, target, member, ref temp);
                    if (useLocals || member.IsRequired)
                    {
                        sb.Append(loop).AppendLine("            __s" + index + " = true;");
                    }

                    sb.Append(loop).AppendLine("            continue;");
                    sb.Append(loop).AppendLine("        }");
                    sb.AppendLine();
                }

                sb.Append(loop).AppendLine("        break;");
            }

            sb.Append(loop).AppendLine("}");
            sb.AppendLine();

            sb.Append(loop).AppendLine("if (options.PropertyNameCaseInsensitive)");
            sb.Append(loop).AppendLine("{");
            foreach (MemberModel member in model.Members)
            {
                if (!writable.Contains(member))
                {
                    continue;
                }

                int index = model.Members.IndexOf(member);
                sb.Append(loop).AppendLine("    if (" + Support + "NameEqualsIgnoreCase(__name, __k" + index + "))");
                sb.Append(loop).AppendLine("    {");
                sb.Append(loop).AppendLine("        reader.Advance();");
                string target = useLocals ? "__v" + index : "__result." + member.MemberName;
                EmitReadInto(sb, loop + "        ", member.Type, target, member, ref temp);
                if (useLocals || member.IsRequired)
                {
                    sb.Append(loop).AppendLine("        __s" + index + " = true;");
                }

                sb.Append(loop).AppendLine("        continue;");
                sb.Append(loop).AppendLine("    }");
            }

            sb.Append(loop).AppendLine("}");
            sb.AppendLine();

            if (model.ExtensionData != null)
            {
                string valueType = Display.FullName(model.ExtensionValueType);
                sb.Append(loop).AppendLine("string __key = reader.GetString();");
                sb.Append(loop).AppendLine("reader.Advance();");
                sb.Append(loop).AppendLine("if (__extra == null)");
                sb.Append(loop).AppendLine("{");
                sb.Append(loop).AppendLine("    __extra = new " + ExtensionDataCreationType(model) + "();");
                if (!useLocals)
                {
                    sb.Append(loop).AppendLine("    __result." + model.ExtensionData.MemberName + " = __extra;");
                }

                sb.Append(loop).AppendLine("}");
                sb.Append(loop).AppendLine();
                int extraTemp = temp++;
                sb.Append(loop).AppendLine(valueType + " __xv" + extraTemp + " = default(" + valueType + ");");
                EmitReadInto(sb, loop, model.ExtensionValueType, "__xv" + extraTemp, null, ref temp);
                sb.Append(loop).AppendLine("__extra[__key] = __xv" + extraTemp + ";");
            }
            else
            {
                sb.Append(loop).AppendLine("reader.SkipValue();");
            }

            sb.Append(indent).AppendLine("}");
            sb.AppendLine();

            for (int i = 0; i < model.Members.Count; i++)
            {
                MemberModel member = model.Members[i];
                if (!member.IsRequired || !writable.Contains(member))
                {
                    continue;
                }

                sb.Append(indent).AppendLine("if (!__s" + i + " && options.ThrowOnMissingRequired)");
                sb.Append(indent).AppendLine("{");
                sb.Append(indent).AppendLine("    " + Support + "ThrowMissingRequired(" + Literal(member.JsonName) + ", " + Literal(model.Symbol.ToDisplayString()) + ");");
                sb.Append(indent).AppendLine("}");
            }

            if (useLocals)
            {
                EmitConstruction(sb, indent, model, writable);
            }
            else
            {
                sb.Append(indent).AppendLine("return __result;");
            }
        }

        private string ExtensionDataCreationType(TypeModel model)
        {
            ITypeSymbol declared = model.ExtensionData.Type;
            if (declared.TypeKind == TypeKind.Interface)
            {
                return "global::System.Collections.Generic.Dictionary<string, " + Display.FullName(model.ExtensionValueType) + ">";
            }

            return Display.FullName(declared);
        }

        private void EmitConstruction(StringBuilder sb, string indent, TypeModel model, List<MemberModel> writable)
        {
            string type = model.TypeName;
            List<string> arguments = new List<string>();

            if (model.Constructor != null)
            {
                for (int i = 0; i < model.Constructor.Parameters.Length; i++)
                {
                    IParameterSymbol parameter = model.Constructor.Parameters[i];
                    MemberModel match = model.Members.FirstOrDefault(m => m.ConstructorParameterIndex == i);
                    if (match != null)
                    {
                        arguments.Add("__v" + model.Members.IndexOf(match));
                    }
                    else
                    {
                        arguments.Add("default(" + Display.FullName(parameter.Type) + ")");
                    }
                }
            }

            List<string> initializers = new List<string>();
            List<MemberModel> deferred = new List<MemberModel>();

            foreach (MemberModel member in writable)
            {
                if (member.ConstructorParameterIndex >= 0)
                {
                    continue;
                }

                int index = model.Members.IndexOf(member);
                if (member.IsInitOnly || member.IsRequired)
                {
                    initializers.Add(member.MemberName + " = __v" + index);
                }
                else if (member.CanWrite)
                {
                    deferred.Add(member);
                }
            }

            if (model.ExtensionData != null && model.ExtensionData.CanWrite && !model.ExtensionData.IsInitOnly)
            {
                deferred.Add(model.ExtensionData);
            }

            string construction = type + " __result = new " + type + "(" + string.Join(", ", arguments) + ")";
            if (initializers.Count > 0)
            {
                construction += " { " + string.Join(", ", initializers) + " }";
            }

            sb.Append(indent).AppendLine(construction + ";");

            foreach (MemberModel member in deferred)
            {
                if (ReferenceEquals(member, model.ExtensionData))
                {
                    sb.Append(indent).AppendLine("if (__extra != null)");
                    sb.Append(indent).AppendLine("{");
                    sb.Append(indent).AppendLine("    __result." + member.MemberName + " = __extra;");
                    sb.Append(indent).AppendLine("}");
                    continue;
                }

                int index = model.Members.IndexOf(member);
                sb.Append(indent).AppendLine("if (__s" + index + ")");
                sb.Append(indent).AppendLine("{");
                sb.Append(indent).AppendLine("    __result." + member.MemberName + " = __v" + index + ";");
                sb.Append(indent).AppendLine("}");
            }

            if (model.ExtensionData != null && model.ExtensionData.IsInitOnly)
            {
                sb.Append(indent).AppendLine("// extension data init-only non supportee");
            }

            sb.Append(indent).AppendLine("return __result;");
        }

        private static int Utf8Length(string value)
        {
            return Encoding.UTF8.GetByteCount(value);
        }

        private static bool CanBeNull(ITypeSymbol type)
        {
            return type.IsReferenceType || type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
        }

        private string NotDefaultExpression(ITypeSymbol type, string access)
        {
            if (CanBeNull(type))
            {
                return access + " != null";
            }

            if (type.TypeKind == TypeKind.Enum || IsSimpleComparable(type))
            {
                return access + " != default(" + Display.FullName(type) + ")";
            }

            return "!global::System.Collections.Generic.EqualityComparer<" + Display.FullName(type) + ">.Default.Equals(" + access + ", default(" + Display.FullName(type) + "))";
        }

        private static bool IsSimpleComparable(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean:
                case SpecialType.System_Byte:
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_Decimal:
                case SpecialType.System_Char:
                case SpecialType.System_DateTime:
                    return true;
                default:
                    return TypeHelpers.Is(type, "System.Guid") || TypeHelpers.Is(type, "System.TimeSpan") || TypeHelpers.Is(type, "System.DateTimeOffset");
            }
        }

        internal static string Literal(string value)
        {
            if (value == null)
            {
                return "null";
            }

            StringBuilder builder = new StringBuilder(value.Length + 2);
            builder.Append('"');
            foreach (char c in value)
            {
                switch (c)
                {
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    default:
                        if (c < 0x20 || c > 0x7E)
                        {
                            builder.Append("\\u").Append(((int)c).ToString("X4"));
                        }
                        else
                        {
                            builder.Append(c);
                        }

                        break;
                }
            }

            builder.Append('"');
            return builder.ToString();
        }
    }
}
