using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace NdJson.SourceGeneration
{
    internal sealed partial class Emitter
    {
        private string GetEnumHelper(INamedTypeSymbol enumType)
        {
            string name;
            if (!_enumHelpers.TryGetValue(enumType, out name))
            {
                name = "global::NdJson.Generated.NdjsonEnum_" + Display.HelperName(enumType);
                _enumHelpers[enumType] = name;
                _enumOrder.Add(enumType);
            }

            return name;
        }

        internal string EmitEnumHelpers()
        {
            if (_enumOrder.Count == 0)
            {
                return null;
            }

            StringBuilder sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();
            sb.AppendLine("namespace NdJson.Generated");
            sb.AppendLine("{");

            foreach (INamedTypeSymbol enumType in _enumOrder)
            {
                EmitEnumHelper(sb, enumType);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private void EmitEnumHelper(StringBuilder sb, INamedTypeSymbol enumType)
        {
            string className = "NdjsonEnum_" + Display.HelperName(enumType);
            string typeName = Display.FullName(enumType);
            bool unsigned = enumType.EnumUnderlyingType != null && enumType.EnumUnderlyingType.SpecialType == SpecialType.System_UInt64;

            NamingPolicy naming = NamingPolicy.Unchanged;
            bool typeForcesString = false;
            AttributeData enumAttribute = AttributeHelper.Find(enumType, _known.EnumString);
            if (enumAttribute != null)
            {
                typeForcesString = AttributeHelper.GetConstructorBool(enumAttribute, 0, true);
                int value = AttributeHelper.GetNamedInt(enumAttribute, "NamingPolicy", (int)NamingPolicy.Inherit);
                if (value != (int)NamingPolicy.Inherit)
                {
                    naming = (NamingPolicy)value;
                }
            }

            List<KeyValuePair<string, IFieldSymbol>> members = new List<KeyValuePair<string, IFieldSymbol>>();
            foreach (ISymbol symbol in enumType.GetMembers())
            {
                IFieldSymbol field = symbol as IFieldSymbol;
                if (field == null || !field.HasConstantValue)
                {
                    continue;
                }

                string name = null;
                AttributeData memberAttribute = AttributeHelper.Find(field, _known.EnumMember);
                if (memberAttribute != null)
                {
                    name = AttributeHelper.GetConstructorString(memberAttribute, 0);
                }

                members.Add(new KeyValuePair<string, IFieldSymbol>(string.IsNullOrEmpty(name) ? Naming.Convert(field.Name, naming) : name, field));
            }

            sb.AppendLine("    internal static class " + className);
            sb.AppendLine("    {");

            for (int i = 0; i < members.Count; i++)
            {
                sb.AppendLine("        private static readonly byte[] __q" + i + " = " + Support + "EncodeQuoted(" + Literal(members[i].Key) + ");");
                sb.AppendLine("        private static readonly byte[] __b" + i + " = " + Support + "EncodeUtf8(" + Literal(members[i].Key) + ");");
            }

            sb.AppendLine();
            sb.AppendLine("        internal static void Write(ref " + Ndj + "JsonWriter writer, " + typeName + " value, " + Ndj + "NdjsonOptions options, bool forceString)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (forceString || " + (typeForcesString ? "true" : "false") + " || options.WriteEnumsAsStrings)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (value)");
            sb.AppendLine("                {");

            HashSet<long> emitted = new HashSet<long>();
            for (int i = 0; i < members.Count; i++)
            {
                long numeric = ToInt64(members[i].Value.ConstantValue, unsigned);
                if (!emitted.Add(numeric))
                {
                    continue;
                }

                sb.AppendLine("                    case " + typeName + "." + members[i].Value.Name + ":");
                sb.AppendLine("                        writer.WritePreEncodedString(__q" + i + ");");
                sb.AppendLine("                        return;");
            }

            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                writer.WriteNumber((long)value);");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            writer.WriteNumber((long)value);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static " + typeName + " Read(ref " + Ndj + "JsonReader reader, " + Ndj + "NdjsonOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (reader.TokenType == " + Ndj + "JsonTokenType.Number)");
            sb.AppendLine("            {");
            sb.AppendLine("                return (" + typeName + ")reader.GetInt64();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            if (reader.TokenType == " + Ndj + "JsonTokenType.Null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return default(" + typeName + ");");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            global::System.ReadOnlySpan<byte> __name = reader.GetUnescapedSpan();");
            sb.AppendLine("            switch (__name.Length)");
            sb.AppendLine("            {");

            foreach (IGrouping<int, int> group in Enumerable.Range(0, members.Count).GroupBy(i => Encoding.UTF8.GetByteCount(members[i].Key)))
            {
                sb.AppendLine("                case " + group.Key + ":");
                foreach (int index in group)
                {
                    sb.AppendLine("                    if (" + Support + "NameEquals(__name, __b" + index + "))");
                    sb.AppendLine("                    {");
                    sb.AppendLine("                        return " + typeName + "." + members[index].Value.Name + ";");
                    sb.AppendLine("                    }");
                }

                sb.AppendLine();
                sb.AppendLine("                    break;");
            }

            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return ReadSlow(reader.GetString());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static " + typeName + " ReadSlow(string text)");
            sb.AppendLine("        {");
            sb.AppendLine("            " + typeName + " parsed;");
            sb.AppendLine("            if (global::System.Enum.TryParse<" + typeName + ">(text, true, out parsed))");
            sb.AppendLine("            {");
            sb.AppendLine("                return parsed;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            long numeric;");
            sb.AppendLine("            if (long.TryParse(text, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out numeric))");
            sb.AppendLine("            {");
            sb.AppendLine("                return (" + typeName + ")numeric;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            " + Support + "ThrowUnknownEnum(text, " + Literal(enumType.ToDisplayString()) + ");");
            sb.AppendLine("            return default(" + typeName + ");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static long ToInt64(object value, bool unsigned)
        {
            if (value == null)
            {
                return 0;
            }

            if (unsigned)
            {
                return unchecked((long)Convert.ToUInt64(value, System.Globalization.CultureInfo.InvariantCulture));
            }

            return Convert.ToInt64(value, System.Globalization.CultureInfo.InvariantCulture);
        }

        private void EmitPolymorphicConverter(StringBuilder sb, string indent, TypeModel model)
        {
            string type = model.TypeName;
            string className = model.ConverterName;

            List<DerivedModel> ordered = model.Derived
                .Select((d, index) => new { d, index, depth = Depth(d.Type) })
                .OrderByDescending(entry => entry.depth)
                .ThenBy(entry => entry.index)
                .Select(entry => entry.d)
                .ToList();

            sb.Append(indent).AppendLine(model.Accessibility + " sealed class " + className + " : global::NdJson.Serialization.NdjsonConverter<" + type + ">");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    public static readonly " + className + " Instance = new " + className + "();");
            sb.AppendLine();
            sb.Append(indent).AppendLine("    private static readonly byte[] __disc = " + Support + "EncodeName(" + Literal(model.Discriminator) + ");");
            sb.Append(indent).AppendLine("    private static readonly byte[] __discKey = " + Support + "EncodeUtf8(" + Literal(model.Discriminator) + ");");

            for (int i = 0; i < ordered.Count; i++)
            {
                sb.Append(indent).AppendLine("    private static readonly byte[] __tag" + i + " = " + Support + "EncodeQuoted(" + Literal(ordered[i].Discriminator) + ");");
            }

            sb.AppendLine();
            sb.Append(indent).AppendLine("    public override void Write(ref " + Ndj + "JsonWriter writer, in " + type + " value, " + Ndj + "NdjsonOptions options)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        if (value == null)");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            writer.WriteNull();");
            sb.Append(indent).AppendLine("            return;");
            sb.Append(indent).AppendLine("        }");
            sb.AppendLine();

            for (int i = 0; i < ordered.Count; i++)
            {
                DerivedModel derived = ordered[i];
                string derivedName = Display.FullName(derived.Type);
                bool isSelf = SymbolEqualityComparer.Default.Equals(derived.Type, model.Symbol);

                sb.Append(indent).AppendLine("        " + derivedName + " __d" + i + " = value as " + derivedName + ";");
                sb.Append(indent).AppendLine("        if (__d" + i + " != null)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            writer.WriteStartObject();");
                sb.Append(indent).AppendLine("            writer.WritePropertyName(__disc);");
                sb.Append(indent).AppendLine("            writer.WritePreEncodedString(__tag" + i + ");");
                sb.Append(indent).AppendLine("            " + MembersWriterExpression(model, derived, isSelf) + ";");
                sb.Append(indent).AppendLine("            writer.WriteEndObject();");
                sb.Append(indent).AppendLine("            return;");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
            }

            if (model.IgnoreUnrecognized)
            {
                sb.Append(indent).AppendLine("        options.GetConverter(value.GetType()).WriteObject(ref writer, value, options);");
            }
            else
            {
                sb.Append(indent).AppendLine("        throw new " + Ndj + "NdjsonException(\"Type derive non declare via [NdjsonDerived] : \" + value.GetType().FullName);");
            }

            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("    public override " + type + " Read(ref " + Ndj + "JsonReader reader, " + Ndj + "NdjsonOptions options)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        if (!reader.BeginObject())");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            return null;");
            sb.Append(indent).AppendLine("        }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("        int __start = reader.TokenStartPosition;");
            sb.Append(indent).AppendLine("        " + Ndj + "JsonReader __scan = reader;");
            sb.Append(indent).AppendLine("        string __tag = null;");
            sb.Append(indent).AppendLine("        while (__scan.ReadNextProperty())");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            if (__scan.PropertyEquals(__discKey))");
            sb.Append(indent).AppendLine("            {");
            sb.Append(indent).AppendLine("                __scan.Advance();");
            sb.Append(indent).AppendLine("                __tag = __scan.GetString();");
            sb.Append(indent).AppendLine("                break;");
            sb.Append(indent).AppendLine("            }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("            __scan.SkipValue();");
            sb.Append(indent).AppendLine("        }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("        if (__tag == null)");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            " + Support + "ThrowMissingDiscriminator(" + Literal(model.Symbol.ToDisplayString()) + ");");
            sb.Append(indent).AppendLine("        }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("        reader.SkipChildren();");
            sb.Append(indent).AppendLine("        " + Ndj + "JsonReader __nested = new " + Ndj + "JsonReader(reader.RawBuffer.Slice(__start, reader.Position - __start), options.MaxDepth);");
            sb.Append(indent).AppendLine("        __nested.Advance();");
            sb.AppendLine();
            sb.Append(indent).AppendLine("        switch (__tag)");
            sb.Append(indent).AppendLine("        {");

            for (int i = 0; i < ordered.Count; i++)
            {
                DerivedModel derived = ordered[i];
                bool isSelf = SymbolEqualityComparer.Default.Equals(derived.Type, model.Symbol);
                sb.Append(indent).AppendLine("            case " + Literal(derived.Discriminator) + ":");
                sb.Append(indent).AppendLine("                return " + MembersReaderExpression(model, derived, isSelf) + ";");
            }

            sb.Append(indent).AppendLine("        }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("        " + Support + "ThrowUnknownDiscriminator(__tag, " + Literal(model.Symbol.ToDisplayString()) + ");");
            sb.Append(indent).AppendLine("        return null;");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private string MembersWriterExpression(TypeModel model, DerivedModel derived, bool isSelf)
        {
            if (isSelf)
            {
                return model.ConverterName + "Members.Instance.WriteMembers(ref writer, __d" + model.Derived.IndexOf(derived) + ", options)";
            }

            string converter;
            if (_converterNames.TryGetValue(derived.Type, out converter))
            {
                return converter + ".Instance.WriteMembers(ref writer, __d" + IndexOfDerived(model, derived) + ", options)";
            }

            return "((global::NdJson.Serialization.INdjsonObjectConverter)options.GetConverter(typeof(" + Display.FullName(derived.Type) + "))).WriteMembers(ref writer, __d" + IndexOfDerived(model, derived) + ", options)";
        }

        private string MembersReaderExpression(TypeModel model, DerivedModel derived, bool isSelf)
        {
            if (isSelf)
            {
                return model.ConverterName + "Members.Instance.Read(ref __nested, options)";
            }

            string converter;
            if (_converterNames.TryGetValue(derived.Type, out converter))
            {
                return converter + ".Instance.Read(ref __nested, options)";
            }

            return "(" + Display.FullName(derived.Type) + ")options.GetConverter(typeof(" + Display.FullName(derived.Type) + ")).ReadObject(ref __nested, options)";
        }

        private static int IndexOfDerived(TypeModel model, DerivedModel derived)
        {
            return model.Derived.IndexOf(derived);
        }

        private static int Depth(ITypeSymbol type)
        {
            int depth = 0;
            ITypeSymbol current = type.BaseType;
            while (current != null)
            {
                depth++;
                current = current.BaseType;
            }

            return depth;
        }

        internal string EmitRegistry(List<TypeModel> models, string assemblyName, bool moduleInitializer)
        {
            string sanitized = Sanitize(assemblyName ?? "Ndjson");

            StringBuilder sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();

            foreach (TypeModel model in models)
            {
                string converter = model.ConverterNamespace.Length == 0
                    ? "global::" + model.ConverterName
                    : "global::" + model.ConverterNamespace + "." + model.ConverterName;
                sb.AppendLine("[assembly: global::NdJson.NdjsonGeneratedConverter(typeof(" + model.TypeName + "), typeof(" + converter + "))]");
            }

            sb.AppendLine();
            sb.AppendLine("namespace NdJson.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class " + sanitized + "NdjsonRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool __registered;");
            sb.AppendLine();

            if (moduleInitializer)
            {
                sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
                sb.AppendLine("        internal static void Initialize()");
                sb.AppendLine("        {");
                sb.AppendLine("            RegisterAll();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("        public static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (__registered)");
            sb.AppendLine("            {");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            __registered = true;");

            foreach (TypeModel model in models)
            {
                string converter = model.ConverterNamespace.Length == 0
                    ? "global::" + model.ConverterName
                    : "global::" + model.ConverterNamespace + "." + model.ConverterName;
                sb.AppendLine("            global::NdJson.Serialization.NdjsonConverterRegistry.Register<" + model.TypeName + ">(" + converter + ".Instance);");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string Sanitize(string value)
        {
            StringBuilder builder = new StringBuilder(value.Length);
            foreach (char c in value)
            {
                builder.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            if (builder.Length == 0 || char.IsDigit(builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }
    }
}
